- README.md
I assume this formula was inline in the text, but now it's already in a code block, so the backticks show. Removed.
> Remove accidental backticks

- concurrency-limits-servlet/src/main/java/com/netflix/concurrency/limits/servlet/ServletLimiterBuilder.java
- concurrency-limits-servlet/src/test/com/netflix/concurrency/limits/GroupServletLimiterTest.java
Looks like there's a bug in ServletLimiterBuilder where the method partitionByPathInfo wasn't using the pathToGroup function. Fixed and updated the tests
> Use pathToGroup function argument in ServletLimiterBuilder

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/Limit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/MetricIds.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Measurement.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/MinimumMeasurement.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/VegasLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/DefaultLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/ImmutableSample.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/AIMDLimitTest.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/VegasLimitTest.java
- For the 'gradient' limiter allow for probing for an up to date noload RTT
- Less aggressive min rtt threshold of (1 us) now that we can probe for better RTT
- Make the sample window size relative to the last min RTT and not the absolute min RTT to get a more meaningful sample size
- Track metrics as distributions and not gauges for better visibility
> Probe for more up to date noload RTT

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Measurement.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/MinimumMeasurement.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/DefaultLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/ImmutableSample.java
- concurrency-limits-grpc/build.gradle
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/Example.java
- Fix bug filtering sample window for high noload RTT
- Continue using the existing sample window when it fails the filter to avoid starving the algorithm
- Set limit to queueSize when probing for minRtt
- Add GRPC example
> Improve probing for new noload RTT in gradient

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/DefaultLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/ImmutableSampleWindow.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/AIMDLimitTest.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/VegasLimitTest.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/DriverBuilder.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/Example.java
- Fix race condition with updating the minimum sample window
- Fix bug in tracking the max inflight requests
- Put safeguards on probing for lower noload rtt
> Make RTT probing less aggressive

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/LifoBlockingLimiter.java
Decorator to the gradient limiter behavior allowing for a time and size limited backlog of requests to help deal with bursty traffic and reduce load shedding in favor of higher availability.
> Blocking limiter with size and time bounds

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractPartitionedLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/BlockingLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/SimpleLimiter.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limiter/BlockingLimiterTest.java
Add an optional timeout to BlockingLimiter, and fix a bug in SimpleLimiter
1. Fix a bug in SimpleLimiter - it fails if inflight > maxInflight, but
should be >=.
2. Improve the limiter builders; should not be generified until they
need to be (e.g. SimpleLimiter should basically never care, because it
doesn't use the context type much).
3. Add an optional timeout to BlockingLimiter, so that users can e.g.
block for up to a minute, and then fail.
> Add an optional timeout to BlockingLimiter

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Gradient2Limit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/WindowedLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/measurement/ExpAvgMeasurement.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractPartitionedLimiter.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/ExpAvgMeasurementTest.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/Driver.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/Example.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/LatencyCollector.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/PartitionedExample.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/TestServer.java
This PR contains two sets of changes that are related in that one improves the performance of the other.  
The first change fixes some issues with poor tracking of long and short term latency measurements in gradient2.  The fix is to track the minimum during a warmup period and then switch to exponential average.  This fixes the need to pick arbitrary operations for reseting the rtt measurements.  
The second change introduces a delay for partitions thereby allowing a server to ensure poorly behaved clients slow down instead of assuming the client will back off.  This is very useful for use cases where a service takes both live and batch traffic where excessive load from live traffic should be rejected immediately and retried on another server but batch traffic will be forced to slow …
> feature: gradient2 fixes + server side delay

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Gradient2Limit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/measurement/ExpAvgMeasurement.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/measurement/SingleMeasurement.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/ExpAvgMeasurementTest.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/Example.java
Fix drift in gradient2 by not smoothing the short term rtt and allowing the long rtt measurement to reduce on faster rtt
> Fix gradient2 drift

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/BlockingLimiter.java
Found this fun bug when trying to use this library with java 11 runtime. Turns out that in jdk 11 (or some prior version newer than 8) behaviour of Instant.now changed slightly such that it attempts to provide higher than millisecond resolution, previously `Instant.now()` would only ever return up to milliseconds but in 11 it returns up to microsecond resolution. Hence it can happen in java 11 that `now.isBefore(deadline)` is true but `Duration.between(now, deadline).toMillis()` rounds to 0 which results in a deadlock if no one ever calls `unblock`
> Make sure that lock.wait in BlockingLimiter is never called with 0 timeout

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/functions/Log10RootFunction.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/VegasLimitTest.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/functions/Log10RootFunctionTest.java
Hi!
I've noticed an inconsistency in the `log10` function where `Log10RootFunction` uses `sqrt` instead of `log10`. As far as I understand from the javadoc, this is not by design.
> Fix Vegas log10 function

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/ImmutableSampleWindow.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/WindowedLimit.java
- precondition for `maxWindowTime()` now allows to pass timeunits bigger than milliseconds
- distinguish builder error messages between `maxWindowTime` and `minWindowTime`
- typo in `ImmutableSampleWindow`: averaTe -> averaGe
> WindowedLimit builder precondition fix and small cleanup:

- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/ConcurrencyLimitServerInterceptorTest.java
Add a delay to unit tests since the listener is invoked AFTER the response is sent to the client.
> Fix unit tests

- concurrency-limits-grpc/src/main/java/com/netflix/concurrency/limits/grpc/server/ConcurrencyLimitServerInterceptor.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/ConcurrencyLimitServerInterceptorTest.java
We've seen situations where server interceptor close or onCancel is never invoked resulting a the inflight counter not being decremented.  Adding an additional hook via Context's cancellation listener should help address that.
> grpc: Handle context cancellation

- concurrency-limits-grpc/src/main/java/com/netflix/concurrency/limits/grpc/client/ConcurrencyLimitClientInterceptor.java
Close rejected requests in halfClose() to allow for the entire call sequence to complete since previously invoked interceptors may need to capture it.
> Improve GRPC client call rejection

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Gradient2Limit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/WindowedLimit.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/Example.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/example/PartitionedExample.java
- Introduce tolerance to gradient2 for more permissive limit growth
- Completely drop windowed samples that are not ready.  For low RPS services these sample could eventually contain a very low RTT candidate (for example, if all the calls were healthchecks)
> Improved stability

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/WindowedLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/window/ImmutableAverageSampleWindow.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/window/ImmutablePercentileSampleWindow.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/window/SampleWindow.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/window/ImmutableAverageSampleWindowTest.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/window/ImmutablePercentileSampleWindowTest.java
- concurrency-limits-grpc/src/main/java/com/netflix/concurrency/limits/grpc/server/ConcurrencyLimitServerInterceptor.java
- concurrency-limits-grpc/src/main/java/com/netflix/concurrency/limits/grpc/server/GrpcServerLimiterBuilder.java
- concurrency-limits-grpc/src/test/java/com/netflix/concurrency/limits/grpc/server/ConcurrencyLimitServerInterceptorTest.java
Currently, we only track latency measurements for successful responses.  This means that limit is not properly updated when all requests time out.
> Include error latency

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/executors/BlockingAdaptiveExecutor.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/executors/UncheckedTimeoutException.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/executor/BlockingAdaptiveExecutorSimulation.java
Provide an UncheckedTimeoutException for runnables to indicate timeouts to BlockingAdaptiveExecutor.
> executor: Add UncheckedTimeoutException

- .travis.yml
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-grpc/build.gradle
- concurrency-limits-grpc/src/main/java/com/netflix/concurrency/limits/grpc/server/ConcurrencyLimitServerInterceptor.java
- Stop treating cancelled as timeouts (for gRPC) as poor client behavior can adversely affect the server concurrency limiter
- For `gradient` make the backoff ratio for drops configurable and change the default to 0.9 (from 0.5) since the current default can result in overly aggressive load shedding.
> Ignore cancelled

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/LifoBlockingLimiter.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limiter/LifoBlockingLimiterTest.java
If a token was acquired around the same time that an operation
timed out, then the token would get lost. That means that the
limiter's capacity would effectively be reduced by one. If
this happens enough times, or the limit is decreased enough
for other reasons, then this would cause to the limiter to
permanently not let any operations through anymore.
> Fix race condition in LifoBlockingLimiter

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/AIMDLimit.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/AIMDLimitTest.java
after talking with @jolynch this section doesn't make sense if the next line bounds the limit between the min/max. #155 
mentioned in #72
> With AIMD, this works moderately well - eventually the client goes above the rate limit and a request is dropped. The next window, the concurrency is dropped by half, which generally will correspondingly drop the concurrency too, and cause the rate limit to be missed.
tangentially related to issue #147.
> don't drop by half periodically.

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/SimpleLimiter.java
Use a Semaphore in SimpleLimiter to manage access in a thread-safe manner.
Fixes #140.
> Use a counting semaphore in SimpleLimiter

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/SimpleLimiter.java
Currently, the inflight metrics only update when a successful listener is acquired. However, in cases where all inflight requests are tied up and everything is being rejected, the inflight counter never updates. This causes the metric to eventually fall off and "appear" as 0 inflight. This change always publishes the inflight distribution to ensure it is always published with its current value.
> Ensure the inflight metrics are properly updated when rejecting

- .github/workflows/nebula-publish.yml
Current config triggers the publish github action job twice resulting in one of the builds to fail.
Updated the config to only run the action once on a new tag push.
> Prevent duplicate publishing on release

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractPartitionedLimiter.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limiter/AbstractPartitionedLimiterTest.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limiter/SimpleLimiterTest.java
Swap `busy` from an `int` to `AtomicInteger`, which eliminates need for a `release` to take the lock.
And while we are here, slim down the work done while holding the lock.
> Reduce contention a little in AbstractPartitionedLimiter

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/MetricRegistry.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Gradient2Limit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/GradientLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/VegasLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractPartitionedLimiter.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/SimpleLimiter.java
- concurrency-limits-spectator/src/main/java/com/netflix/concurrency/limits/spectator/SpectatorMetricRegistry.java
Add two methods to SampleListener, addLongSample and addDoubleSample, which accept primitives and avoid boxing; default implementations are provided for backwards compatibility.
> Add methods to SampleListener to handle primitives

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/Gradient2Limit.java
Use IntUnaryOperator in Gradient2Limit for queueSize to avoid boxing. Also, avoid excessive volatile reads and avoid boxing when debug logging is disabled.
> Use IntUnaryOperator in Gradient2Limit for queueSize

- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/VegasLimit.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/functions/Log10RootFunction.java
- concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/functions/Log10RootIntFunction.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/VegasLimitTest.java
- concurrency-limits-core/src/test/java/com/netflix/concurrency/limits/limit/functions/Log10RootIntFunctionTest.java
Switch to IntUnaryOperator and DoubleUnaryOperator in VegasLimit to avoid unnecessary boxing. Additionally, reduced repeated reads of volatile fields.
> Use IntUnaryOperator / DoubleUnaryOperator in VegasLimit
